
    <div><br/></div>
    <br>
    <table>
        <tr>
            <th><label>Shortcode</label></th>
            <th><label>Expiration</label></th>
            <th><label>Action</label></th>
        </tr>
        <tbody>
            <tr>
                <td><code></code></td>
                <td></td>
                <td>
                </td>
                <td>
                </td>
                <td></td>
            </tr>
        </tbody>
    </table>
    <br>
</div>
